apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-app
